root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ./cmd/${SERVICE:-collector}"
delay = 500
exclude_dir = ["tmp", "target", "vendor", ".git"]
exclude_regex = ["_test\\.go$"]
include_ext = ["go", "toml", "yaml"]
kill_delay = "1s"
log = "tmp/build-errors.log"
send_interrupt = true
stop_on_error = false

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
